FROM php:8.0-fpm-buster

# Update and install common packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    g++ \
    unzip \
    curl \
    iputils-ping \
    wget \
    htop \
    apt-utils \
    gnupg \
    software-properties-common \
    apt-transport-https \
    libxml2-dev \
    vim

# Update and install common packages
RUN apt-get update && apt-get install --no-install-recommends -y \
    libaio-dev \
    freetds-dev \
    libssl-dev \
    openssl \
    supervisor

# Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer --version=2.1.6 \
    && composer --version

# Install PDO
RUN apt-get install -y libpq-dev \
    && docker-php-ext-install pdo pdo_mysql pdo_pgsql

# OPcache
RUN docker-php-ext-configure opcache --enable-opcache \
    && docker-php-ext-install opcache

RUN apt-get update && apt-get install -y \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libmcrypt-dev \
        libpng-dev \
        vim \
    && docker-php-ext-install -j$(nproc) iconv bcmath \
    && docker-php-ext-install -j$(nproc) gd

RUN apt-get install -y zlib1g-dev libicu-dev g++ libzip-dev git && \
    docker-php-ext-configure intl && \
    docker-php-ext-install intl zip sockets && \
    apt-get purge -y g++

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

RUN echo 'deb [trusted=yes] https://repo.symfony.com/apt/ /' | tee /etc/apt/sources.list.d/symfony-cli.list \
    apt update \
    apt install symfony-cli
    
ENV TZ=Europe/Madrid